[package]
name = "lan-mouse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.2"
trust-dns-resolver = "0.22"
memmap = "0.7"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
threadpool = "1.8"

[target.'cfg(unix)'.dependencies]
wayland-client = { version="0.30.0" }
wayland-protocols = { version="0.30.0", features=["client", "staging", "unstable"] }
wayland-protocols-wlr = { version="0.1.0", features=["client"] }
wayland-protocols-misc = { version="0.1.0", features=["client"] }
wayland-protocols-plasma = { version="0.1.0", features=["client"] }
x11 = { version = "2.21.0", features = ["xlib", "xtest"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
